### ISSUE TITLE
Do you plan to also release the adapted checkpoints for each experiment? 

### ISSUE THREAD

**Issue by chenxshuo** [ylsung/VL_adapter#14]
Hi guys, thanks a lot for this great repo and work! 

I wonder whether you are planning to also release the adapted model checkpoints used for each final evaluation.

Thanks again and looking forward to your reply~

**Comment by ylsung** [comment]
I will check the storage and get back to you if the checkpoints are still there.

**Comment by chenxshuo** [comment]
Hi @ylsung , thanks for your reply, really appreciate that!

**Comment by ylsung** [comment]
Sorry for the late reply. I found our old storage is thrown away, so my checkpoints are also not available.

**Comment by chenxshuo** [comment]
> Sorry for the late reply. I found our old storage is thrown away, so my checkpoints are also not available.

Ok, no problem but thanks anyway!
