### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by kmzcy** [ylsung/VL_adapter#2]
When I run ‘bash scripts/image/single_adapter.sh 1’, I met error like this:
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/data/VL_adapter-main/datasets/COCO/clip_features/data_clip_RN101_att/COCO_val2014_000000007414.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Would you mind telling me how can I get this .h5 file?
Thank you.

**Comment by ylsung** [comment]
I just put the data on a drive, the link is [here](https://drive.google.com/file/d/1O_RU1iFh_sbItZCTkOHUrbVIQQ_89Djj/view). You can use [gdrive](https://github.com/prasmussen/gdrive) cli to download it. I also updated the Data session in the README. Let me know if you run into any issues running it.

**Comment by kmzcy** [comment]
Thanks for your reply！ This really helps a lot. By the way, does the part of your paper in the screenshot included in this code?
![957](https://user-images.githubusercontent.com/86351670/163954789-abe749e1-b189-4134-838b-054cf83eff77.png)

**Comment by ylsung** [comment]
CLIP-ViL is not in the repo right now. I am working on it, and I will let you know when it is ready.

**Comment by ylsung** [comment]
@kmzcy The codes for CLIP-ViL are included. Please check them out if you're interested.
