### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by wytszhuzhu** [ylsung/VL_adapter#3]
it's a nice work,but there is a problem when i train the shell(bash scripts/image/multiple_adapters.sh 1).i find the problem in github,it seems about out of memory though i set the batch_size very small(20 or 10,my GPU is 2080ti(11G)).Do you know why is that?
![无标题](https://user-images.githubusercontent.com/49281157/167568751-c6b2e04b-368e-4d09-8565-7fd804a2cf6b.png)
,
![无1题](https://user-images.githubusercontent.com/49281157/167570322-82e68c87-3f2a-4580-b033-10cdec144988.png)

**Comment by wytszhuzhu** [comment]
Thank you very much! I changed the memory from 32G to 64G and it worked.

**Comment by wytszhuzhu** [comment]
> Do you find the same issue in other scripts? I think it's not because of GPU memory but the RAM. How large is the RAM on your machine?

Thank you very much! I changed the memory from 32G to 64G and it worked.

**Comment by ylsung** [comment]
This is awesome! Glad to help.
