### ISSUE TITLE
Clip feature extraction

### ISSUE THREAD

**Issue by kittitouchar** [ylsung/VL_adapter#4]
This CVPR work is really interesting.
Btw, could you please also provide a script for extracting clip features?

Thank you for sharing this great work!

**Comment by ylsung** [comment]
Thank you for being interested in VL-Adapter. I will release the script for feature extraction soon. Stay tuned!

**Comment by ylsung** [comment]
Sorry for the delay. I added the scripts for extracting CLIP features in `feature_extraction`. Let me know there is any question.
